### ISSUE TITLE
weekOfDay "0" problem

### ISSUE THREAD

**Issue by fatihpolatli** [lirantal/cron-to-quartz#4]
hi,

when weekOfDay is 0 your if clause evaluate that as wrong, so doesnt increment, i changed it this way..

`
 if(num) {
            quartzCompatibleStr += num+1;
        } else {
            quartzCompatibleStr += chr;
        }
`

`if (!isNaN(Number(num))) {
            quartzCompatibleStr += num+1;
        } else {
            quartzCompatibleStr += chr;
        }`

**Comment by lirantal** [comment]
Can you submit a PR to fix it? I'll take a look later

**Comment by fatihpolatli** [comment]
couldnt make it, it says that i have no permission

**Comment by lirantal** [comment]
@fatihpolatli you need to fork the repository to create your own copy, then either commit changes to the `master` branch, or branch off to a bugfix branch and commit/push the code there. Then simply create a new Pull Request, it'll guide you through the process.

**Comment by fatihpolatli** [comment]
i fetch the project with "git fetch", i can see files in my local computer,
when i changed the file, github application see that change and activate
commit screen, i commited it but after that when pulling request it gives
permission error

**Comment by lirantal** [comment]
I'm not sure what you're doing but it looks like you are trying to commit and push back to this repository, which you can't. You need to fork this repository to create your own clone, and then commit and push to your own forked repository. Then we can create a Pull Request with your suggested changes.

I'm pretty sure GitHub has some guidelines for all of this process for new comers.
